### ISSUE TITLE
Not able to import template to local DSW instance

### ISSUE THREAD

**Issue by TassosP78** [ds-wizard/horizon-europe-dmp-template#7]
Hey there, 

I have been trying to import the template either through the ID or via the ZIP file. When importing using the ID I get an "Unable to import document" error, while when using the ZIP I got "template.json" was not found in archive" although the file is idd included in the archive. No issues with importing the H2020 one. 

Any ideas? 

Thanks for the help!

**Comment by MarekSuchanek** [comment]
Hello, sorry for the late reply... what is the procedure for getting the ZIP file?
